# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odvehicle',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
