# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_odvehicle_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odvehicle',
            name='photo',
            field=models.ImageField(default='media/upload/no-img.png', upload_to='media/upload/'),
        ),
    ]
